name: oliver-cowdery-chatbot
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: danemel/TalkWithOliverCowdery
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: cowdery-app
  routes:
  - path: /
  run_command: gunicorn app:app
  source_dir: /
  envs:
  - key: CLAUDE_API_KEY
    scope: RUN_TIME
    value: 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 